name: GodEquip
version: '1.2-SNAPSHOT'
main: com.solo.godequip.GodEquipPlugin
api-version: '1.20'
description: Adds the Singularity equipment set.
authors: [ Solo ]

commands:
  godset:
    description: Grants the Singularity equipment set.
    usage: /godset
    permission: godequip.admin
